name: browser-tests

on:
  push:
  pull_request:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  tests-testbench-9:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - 8.1
          - 8.2
          - 8.3
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false

    name: PHP${{ matrix.php }} on ${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo, :php-psr
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=orchestra/testbench-dusk:^9.0"

      - name: Installed dependencies
        run: |
          composer show -D

      - name: Upgrade Chrome Driver
        run: php vendor/bin/dusk-updater detect --auto-update

      - name: Create SQLite Database
        run: php vendor/bin/testbench-dusk package:create-sqlite-db

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php vendor/bin/testbench-dusk serve --no-reload &

      - name: Execute tests
        run: vendor/bin/pest -c phpunit.dusk.xml
        env:
          APP_URL: http://127.0.0.1:8000
          DUSK_SERVE_PORT: 8000

  tests-testbench-8:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - 8.1
          - 8.2
          - 8.3
        dependencies:
          - "highest"
          - "lowest"
        experimental:
          - false

    name: PHP${{ matrix.php }} on ${{ matrix.os }} (${{ matrix.dependencies }})

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo, :php-psr
          coverage: none

      - name: Install dependencies
        uses: "ramsey/composer-install@v2"
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=orchestra/testbench-dusk:^8.0"

      - name: Installed dependencies
        run: |
          composer show -D

      - name: Upgrade Chrome Driver
        run: php vendor/bin/dusk-updater detect --auto-update

      - name: Create SQLite Database
        run: php vendor/bin/testbench-dusk package:create-sqlite-db

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux &

      - name: Run Laravel Server
        run: php vendor/bin/testbench-dusk serve --no-reload &

      - name: Execute tests
        run: vendor/bin/pest -c phpunit.dusk.xml
        env:
          APP_URL: http://127.0.0.1:8000
          DUSK_SERVE_PORT: 8000
