name: browser-tests

on:
  push:
    branches:
      - '*.x'
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  tests-testbench-9:
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.experimental }}
    strategy:
      matrix:
        os:
          - "ubuntu-latest"
        php:
          - 8.3
          - 8.4
          - 8.5
        testbench:
          - 9
          - 10
          - 11
        dependencies:
          - "highest"
        experimental:
          - false
        exclude:
          - php: 8.5
            testbench: 9

    name: Testbench:${{ matrix.testbench }} / PHP:${{ matrix.php }} / OS:${{ matrix.os }} ${{ matrix.dependencies == 'highest' && '⬆️' || '⬇️' }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, mysql, mysqli, pdo_mysql, bcmath, intl, fileinfo, :php-psr
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: "${{ matrix.dependencies }}"
          composer-options: "--prefer-dist --no-cache --with=orchestra/testbench-dusk:${{ matrix.os == 'ubuntu-latest' && '^' || '~' }}${{ matrix.testbench }}.0"

      - name: Installed dependencies
        run: |
          composer show -D

      - name: Upgrade Chrome Driver
        run: php vendor/bin/dusk-updater detect --auto-update

      - name: Create SQLite Database
        run: php vendor/bin/testbench-dusk package:create-sqlite-db

      - name: Start Chrome Driver
        run: ./vendor/laravel/dusk/bin/chromedriver-linux --port=9515 &

      - name: Run Laravel Server
        run: php vendor/bin/testbench-dusk serve --no-reload &

      - name: Execute tests
        run: vendor/bin/pest -c phpunit.dusk.xml --display-deprecations --fail-on-deprecation
        env:
          APP_URL: http://127.0.0.1:8000
          DUSK_SERVE_PORT: 8000
